### ISSUE TITLE
Did the PyPI-published Flask-CSV 1.2.0 get changed somehow?

### ISSUE THREAD

**Issue by alichaudry** [Shir0kamii/flask-CSV#10]
My application that uses Flask-CSV 1.2.0 stopped working all of a sudden with the following error:

```python
TypeError: send_file() got an unexpected keyword argument 'download_name'
```

I upgraded to 1.2.1 and I get the same error. 1.2.0 has been working fine for a couple years now; did something change and get published to PyPI accidentally?

**Comment by alichaudry** [comment]
So I installed a fresh Flask-CSV 1.2.0 (the version that's basically been the only release since 2018, till last week) and it's showing me the change from last week. Definitely seems like this code change got pushed through to version 1.2.0 on PyPI.

<img width="898" alt="image" src="https://github.com/Shir0kamii/Flask-CSV/assets/15057353/6a275938-f943-4bf2-83dc-29de79f45224">

**Comment by Shir0kamii** [comment]
Indeed, it seems I made a mistake while releasing the new version. It should be fixed now, can you confirm it?

**Comment by alichaudry** [comment]
Seems to be back to where it was before.

![image](https://github.com/Shir0kamii/Flask-CSV/assets/15057353/d4843a38-0e2d-4338-a4d1-5b24b43b89d5)

**Comment by alichaudry** [comment]
All set now, closing.
