### ISSUE TITLE
DictWriter's kwargs interface missing

### ISSUE THREAD

**Issue by SyedMuhammadAli** [Shir0kamii/flask-CSV#6]
To ignore extra columns in the given dict, DictWriter has a extrasaction='ignore' kwarg. I can't seem to find an interface to send that arg to the internal writer

Without this, if the header is shorter than the keys in dict, there's a ValueError exception

**Comment by Shir0kamii** [comment]
You are right, I didn't think about this case.

I've just released the 1.2.0 version with this functionnality. Please use the *writer_kwargs* argument. You can see it in action on the [updated README](https://github.com/Shir0kamii/Flask-CSV#passing-additionnal-parameters)
