### ISSUE TITLE
flask api changes

### ISSUE THREAD

**Issue by amg-web** [Shir0kamii/flask-CSV#8]
https://flask.palletsprojects.com/en/2.2.x/changes/?highlight=send_file#version-2-2-0

you need to update send_file() arguments or use requirements with versions

**Comment by rowshi** [comment]
Second this...

**Comment by amg-web** [comment]
@rowshi just drop it.
use example from flask documentation without Flask-CSV

**Comment by Shir0kamii** [comment]
I'm sorry I didn't see this issue until the recent activity. I've merged @rowshi's PR, and will release a new version tonight or tomorrow.

**Comment by Shir0kamii** [comment]
I just released version 1.2.1 with the fix!
